export const categorylist = [
  { id: 1, text: 'React 기본 개념' },
  { id: 2, text: 'React Hooks' },
  { id: 3, text: 'React 렌더링 원리' },
  { id: 4, text: 'React 상태 관리' },
  { id: 5, text: 'React 라우팅' },
  { id: 6, text: 'React 성능 최적화' },
  { id: 7, text: 'TypeScript 기본 문법' },
  { id: 8, text: 'TypeScript 타입과 인터페이스' },
  { id: 9, text: 'TypeScript 제네릭' },
  { id: 10, text: 'React와 TypeScript 함께 사용하기' },
  { id: 11, text: 'JavaScript ES6+' },
  { id: 12, text: 'JavaScript 비동기 처리' },
  { id: 13, text: 'JavaScript 이벤트 루프와 호이스팅' },
  { id: 14, text: 'Redux / Redux Toolkit' },
  { id: 15, text: 'Recoil / Zustand' },
  { id: 16, text: '웹 브라우저 동작 원리' },
  { id: 17, text: '웹 접근성과 SEO' },
  { id: 18, text: 'Webpack / Vite' },
  { id: 19, text: 'Git & GitHub' },
  { id: 20, text: 'HTTP와 REST API' },
];
