import {
  Code2,
  Blocks,
  Layers,
  Database,
  Zap,
  FileCode2,
  Braces,
  Globe,
  GitBranch,
  Server,
  Palette,
  Search,
  Sparkles,
} from 'lucide-react';

export const categorylist = [
  {
    id: 1,
    text: 'React 기본 개념',
    icon: Code2,
    color: 'from-blue-500 to-blue-600',
  },
  {
    id: 2,
    text: 'React Hooks',
    icon: Blocks,
    color: 'from-sky-400 to-sky-500',
  },
  {
    id: 3,
    text: 'React 렌더링 원리',
    icon: Layers,
    color: 'from-indigo-500 to-indigo-600',
  },
  {
    id: 4,
    text: 'React 상태 관리',
    icon: Database,
    color: 'from-violet-500 to-violet-600',
  },
  {
    id: 5,
    text: 'React 성능 최적화',
    icon: Zap,
    color: 'from-purple-500 to-purple-600',
  },
  {
    id: 6,
    text: 'TypeScript 기본 문법',
    icon: FileCode2,
    color: 'from-slate-500 to-slate-600',
  },
  {
    id: 7,
    text: 'React와 TypeScript',
    icon: Braces,
    color: 'from-blue-600 to-blue-700',
  },
  {
    id: 8,
    text: 'JavaScript ES6+',
    icon: Sparkles,
    color: 'from-amber-400 to-amber-500',
  },
  {
    id: 9,
    text: '상태관리 라이브러리',
    icon: Database,
    color: 'from-fuchsia-500 to-fuchsia-600',
  },
  {
    id: 10,
    text: '브라우저 동작 원리',
    icon: Globe,
    color: 'from-emerald-500 to-emerald-600',
  },
  {
    id: 11,
    text: 'Git & GitHub',
    icon: GitBranch,
    color: 'from-gray-500 to-gray-600',
  },
  {
    id: 12,
    text: 'HTTP와 REST API',
    icon: Server,
    color: 'from-teal-500 to-teal-600',
  },
  {
    id: 13,
    text: 'CSS & Tailwind',
    icon: Palette,
    color: 'from-pink-400 to-pink-500',
  },
  {
    id: 14,
    text: 'TanStack Query',
    icon: Search,
    color: 'from-cyan-500 to-cyan-600',
  },
  {
    id: 15,
    text: '기술면접 전범위',
    icon: Sparkles,
    color: 'from-rose-500 to-rose-600',
  },
];
